[package]
name = "wasm_runtime"
version = "0.1.0"
edition = "2021"
authors = ["VMware's Wasm Labs"]
description = "Wrapper for offering a simple C-API to manage WebAssembly modules via Wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
readme = "README.md"
documentation = "https://docs.rs/wasi"


[lib]
crate-type = ["cdylib"]      # Creates dynamic lib
#crate-type = ["staticlib"] # Creates static lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.40.0"
wasmtime-wasi = "0.40.0"
wasi-common = "0.40.0"
wasi-cap-std-sync = "0.40.0"
anyhow = "1.0.19"
once_cell = "1.13.1"

